apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  hostapd.conf: |-
  {{- range $name,$val := .Values.hostapd.extra_options }}
    {{ $name }}={{ $val }}
  {{- end }}
