apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: default
  labels:
    app: hostapd
spec:
  selector:
    matchLabels:
      app: hostapd
  template:
    metadata:
      labels:
        app: hostapd
    spec:
      hostNetwork: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: hostapd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostapd-config
          mountPath: /etc/hostapd.conf
          subPath: hostapd.conf
        resources:
          requests:
            memory: "32Mi"
      volumes:
      - name: hostapd-config
        configMap:
          name: {{ .Release.Name }}-config
